### ISSUE TITLE
The background image should be responsive

### ISSUE THREAD

**Issue by jacobherrington** [devfake/years-to-read#4]
This is more of a design opinion than a bug, but I think the background image should resize with the window.

**Current behavior:**
The background image does not resize, leaving an empty space at the bottom of the screen that looks a bit unintentional.

<img width="1442" alt="screen shot 2018-08-18 at 12 46 51 pm" src="https://user-images.githubusercontent.com/11466782/44301917-1185ec00-a2e5-11e8-9535-df437c517fbb.png">

**Expected behavior:**
The background image resizes with the window.

<img width="1082" alt="screen shot 2018-08-18 at 12 50 05 pm" src="https://user-images.githubusercontent.com/11466782/44301944-a38df480-a2e5-11e8-93c1-f1e97dd9f676.png">

Note that there is still some space, this is due to the background image itself and is unavoidable using the current image:

<img width="1451" alt="screen shot 2018-08-18 at 12 52 43 pm" src="https://user-images.githubusercontent.com/11466782/44301950-b9031e80-a2e5-11e8-9028-878b5830a36e.png">

This would be a great issue for someone looking to learn how to make PRs on GitHub.

**Comment by devfake** [comment]
Thanks for this! The empty space was intended. I had also tried a full background version, but I liked this more. However, I have no problem if someone wants to create a PR for it (:

**Comment by alexweininger** [comment]
Not sure if recognized previously, but on higher resolution displays the background also leaves space on the right. 

For reference - my display is 2560 x 1440 and using Chrome.
![image](https://user-images.githubusercontent.com/12476526/44313825-fb9b2880-a3c3-11e8-8a54-d2585077ee41.png)

**Comment by msfern** [comment]
Referenced in #10
